export interface ChiefComplaint {
  value: string;
  label: string;
}

/** All chief complaint categories known to the trained XGBoost model.
 *  `value` is the exact string expected by the model (from cc_* training columns).
 *  `label` is the human-readable display name. */
export const CHIEF_COMPLAINTS: ChiefComplaint[] = [
  { value: "abdominalcramping", label: "Abdominal Cramping" },
  { value: "abdominaldistention", label: "Abdominal Distention" },
  { value: "abdominalpain", label: "Abdominal Pain" },
  { value: "abdominalpainpregnant", label: "Abdominal Pain (Pregnant)" },
  { value: "abnormallab", label: "Abnormal Lab" },
  { value: "abscess", label: "Abscess" },
  { value: "addictionproblem", label: "Addiction Problem" },
  { value: "agitation", label: "Agitation" },
  { value: "alcoholintoxication", label: "Alcohol Intoxication" },
  { value: "alcoholproblem", label: "Alcohol Problem" },
  { value: "allergicreaction", label: "Allergic Reaction" },
  { value: "alteredmentalstatus", label: "Altered Mental Status" },
  { value: "animalbite", label: "Animal Bite" },
  { value: "ankleinjury", label: "Ankle Injury" },
  { value: "anklepain", label: "Ankle Pain" },
  { value: "anxiety", label: "Anxiety" },
  { value: "arminjury", label: "Arm Injury" },
  { value: "armpain", label: "Arm Pain" },
  { value: "armswelling", label: "Arm Swelling" },
  { value: "assaultvictim", label: "Assault Victim" },
  { value: "asthma", label: "Asthma" },
  { value: "backpain", label: "Back Pain" },
  { value: "bleeding/bruising", label: "Bleeding / Bruising" },
  { value: "blurredvision", label: "Blurred Vision" },
  { value: "bodyfluidexposure", label: "Body Fluid Exposure" },
  { value: "breastpain", label: "Breast Pain" },
  { value: "breathingdifficulty", label: "Breathing Difficulty" },
  { value: "breathingproblem", label: "Breathing Problem" },
  { value: "burn", label: "Burn" },
  { value: "cardiacarrest", label: "Cardiac Arrest" },
  { value: "cellulitis", label: "Cellulitis" },
  { value: "chestpain", label: "Chest Pain" },
  { value: "chesttightness", label: "Chest Tightness" },
  { value: "chills", label: "Chills" },
  { value: "coldlikesymptoms", label: "Cold-like Symptoms" },
  { value: "confusion", label: "Confusion" },
  { value: "conjunctivitis", label: "Conjunctivitis" },
  { value: "constipation", label: "Constipation" },
  { value: "cough", label: "Cough" },
  { value: "cyst", label: "Cyst" },
  {
    value: "decreasedbloodsugar symptomatic",
    label: "Decreased Blood Sugar (Symptomatic)",
  },
  { value: "dehydration", label: "Dehydration" },
  { value: "dentalpain", label: "Dental Pain" },
  { value: "depression", label: "Depression" },
  { value: "detoxevaluation", label: "Detox Evaluation" },
  { value: "diarrhea", label: "Diarrhea" },
  { value: "dizziness", label: "Dizziness" },
  { value: "drug/alcoholassessment", label: "Drug / Alcohol Assessment" },
  { value: "drugproblem", label: "Drug Problem" },
  { value: "dyspnea", label: "Dyspnea" },
  { value: "dysuria", label: "Dysuria" },
  { value: "earpain", label: "Ear Pain" },
  { value: "earproblem", label: "Ear Problem" },
  { value: "edema", label: "Edema" },
  { value: "elbowpain", label: "Elbow Pain" },
  {
    value: "elevatedbloodsugar nosymptoms",
    label: "Elevated Blood Sugar (No Symptoms)",
  },
  {
    value: "elevatedbloodsugar symptomatic",
    label: "Elevated Blood Sugar (Symptomatic)",
  },
  { value: "emesis", label: "Emesis (Vomiting)" },
  { value: "epigastricpain", label: "Epigastric Pain" },
  { value: "epistaxis", label: "Epistaxis (Nosebleed)" },
  { value: "exposuretostd", label: "Exposure to STD" },
  { value: "extremitylaceration", label: "Extremity Laceration" },
  { value: "extremityweakness", label: "Extremity Weakness" },
  { value: "eyeinjury", label: "Eye Injury" },
  { value: "eyepain", label: "Eye Pain" },
  { value: "eyeproblem", label: "Eye Problem" },
  { value: "eyeredness", label: "Eye Redness" },
  { value: "facialinjury", label: "Facial Injury" },
  { value: "faciallaceration", label: "Facial Laceration" },
  { value: "facialpain", label: "Facial Pain" },
  { value: "facialswelling", label: "Facial Swelling" },
  { value: "fall", label: "Fall" },
  { value: "fall>65", label: "Fall (Age 65+)" },
  { value: "fatigue", label: "Fatigue" },
  { value: "femaleguproblem", label: "Female GU Problem" },
  { value: "fever", label: "Fever" },
  { value: "fever 75yearsorolder", label: "Fever (Age 75+)" },
  { value: "fever 9weeksto74years", label: "Fever (9 Weeks - 74 Years)" },
  { value: "feverimmunocompromised", label: "Fever (Immunocompromised)" },
  { value: "fingerinjury", label: "Finger Injury" },
  { value: "fingerpain", label: "Finger Pain" },
  { value: "fingerswelling", label: "Finger Swelling" },
  { value: "flankpain", label: "Flank Pain" },
  { value: "follow upcellulitis", label: "Follow-up: Cellulitis" },
  { value: "footinjury", label: "Foot Injury" },
  { value: "footpain", label: "Foot Pain" },
  { value: "footswelling", label: "Foot Swelling" },
  { value: "foreignbodyineye", label: "Foreign Body in Eye" },
  { value: "fulltrauma", label: "Full Trauma" },
  { value: "generalizedbodyaches", label: "Generalized Body Aches" },
  { value: "gibleeding", label: "GI Bleeding" },
  { value: "giproblem", label: "GI Problem" },
  { value: "groinpain", label: "Groin Pain" },
  { value: "hallucinations", label: "Hallucinations" },
  { value: "handinjury", label: "Hand Injury" },
  { value: "handpain", label: "Hand Pain" },
  { value: "headache", label: "Headache" },
  { value: "headache newonsetornewsymptoms", label: "Headache (New Onset)" },
  {
    value: "headache recurrentorknowndxmigraines",
    label: "Headache (Recurrent / Migraine)",
  },
  { value: "headachere evaluation", label: "Headache Re-evaluation" },
  { value: "headinjury", label: "Head Injury" },
  { value: "headlaceration", label: "Head Laceration" },
  { value: "hematuria", label: "Hematuria (Blood in Urine)" },
  { value: "hemoptysis", label: "Hemoptysis (Coughing Blood)" },
  { value: "hippain", label: "Hip Pain" },
  { value: "homicidal", label: "Homicidal Ideation" },
  { value: "hyperglycemia", label: "Hyperglycemia" },
  { value: "hypertension", label: "Hypertension" },
  { value: "hypotension", label: "Hypotension" },
  { value: "influenza", label: "Influenza" },
  { value: "ingestion", label: "Ingestion" },
  { value: "insectbite", label: "Insect Bite" },
  { value: "irregularheartbeat", label: "Irregular Heartbeat" },
  { value: "jawpain", label: "Jaw Pain" },
  { value: "jointswelling", label: "Joint Swelling" },
  { value: "kneeinjury", label: "Knee Injury" },
  { value: "kneepain", label: "Knee Pain" },
  { value: "laceration", label: "Laceration" },
  { value: "leginjury", label: "Leg Injury" },
  { value: "legpain", label: "Leg Pain" },
  { value: "legswelling", label: "Leg Swelling" },
  { value: "lethargy", label: "Lethargy" },
  { value: "lossofconsciousness", label: "Loss of Consciousness" },
  { value: "maleguproblem", label: "Male GU Problem" },
  { value: "mass", label: "Mass / Lump" },
  { value: "medicalproblem", label: "Medical Problem" },
  { value: "medicalscreening", label: "Medical Screening" },
  { value: "medicationproblem", label: "Medication Problem" },
  { value: "medicationrefill", label: "Medication Refill" },
  { value: "migraine", label: "Migraine" },
  { value: "modifiedtrauma", label: "Modified Trauma" },
  { value: "motorcyclecrash", label: "Motorcycle Crash" },
  { value: "motorvehiclecrash", label: "Motor Vehicle Crash" },
  { value: "multiplefalls", label: "Multiple Falls" },
  { value: "nasalcongestion", label: "Nasal Congestion" },
  { value: "nausea", label: "Nausea" },
  { value: "nearsyncope", label: "Near Syncope" },
  { value: "neckpain", label: "Neck Pain" },
  { value: "neurologicproblem", label: "Neurologic Problem" },
  { value: "numbness", label: "Numbness" },
  { value: "oralswelling", label: "Oral Swelling" },
  { value: "otalgia", label: "Otalgia (Ear Pain)" },
  { value: "other", label: "Other" },
  { value: "overdose accidental", label: "Overdose (Accidental)" },
  { value: "overdose intentional", label: "Overdose (Intentional)" },
  { value: "pain", label: "Pain (General)" },
  { value: "palpitations", label: "Palpitations" },
  { value: "panicattack", label: "Panic Attack" },
  { value: "pelvicpain", label: "Pelvic Pain" },
  { value: "poisoning", label: "Poisoning" },
  { value: "post opproblem", label: "Post-op Problem" },
  { value: "psychiatricevaluation", label: "Psychiatric Evaluation" },
  { value: "psychoticsymptoms", label: "Psychotic Symptoms" },
  { value: "rapidheartrate", label: "Rapid Heart Rate" },
  { value: "rash", label: "Rash" },
  { value: "rectalbleeding", label: "Rectal Bleeding" },
  { value: "rectalpain", label: "Rectal Pain" },
  { value: "respiratorydistress", label: "Respiratory Distress" },
  { value: "ribinjury", label: "Rib Injury" },
  { value: "ribpain", label: "Rib Pain" },
  { value: "seizure newonset", label: "Seizure (New Onset)" },
  { value: "seizure priorhxof", label: "Seizure (Prior History)" },
  { value: "seizures", label: "Seizures" },
  { value: "shortnessofbreath", label: "Shortness of Breath" },
  { value: "shoulderinjury", label: "Shoulder Injury" },
  { value: "shoulderpain", label: "Shoulder Pain" },
  { value: "sicklecellpain", label: "Sickle Cell Pain" },
  { value: "sinusproblem", label: "Sinus Problem" },
  { value: "skinirritation", label: "Skin Irritation" },
  { value: "skinproblem", label: "Skin Problem" },
  { value: "sorethroat", label: "Sore Throat" },
  { value: "stdcheck", label: "STD Check" },
  { value: "strokealert", label: "Stroke Alert" },
  { value: "suicidal", label: "Suicidal Ideation" },
  { value: "suture/stapleremoval", label: "Suture / Staple Removal" },
  { value: "swallowedforeignbody", label: "Swallowed Foreign Body" },
  { value: "syncope", label: "Syncope (Fainting)" },
  { value: "tachycardia", label: "Tachycardia" },
  { value: "testiclepain", label: "Testicle Pain" },
  { value: "thumbinjury", label: "Thumb Injury" },
  { value: "tickremoval", label: "Tick Removal" },
  { value: "toeinjury", label: "Toe Injury" },
  { value: "toepain", label: "Toe Pain" },
  { value: "trauma", label: "Trauma" },
  { value: "unresponsive", label: "Unresponsive" },
  { value: "uri", label: "URI (Upper Respiratory Infection)" },
  { value: "urinaryfrequency", label: "Urinary Frequency" },
  { value: "urinaryretention", label: "Urinary Retention" },
  { value: "urinarytractinfection", label: "Urinary Tract Infection" },
  { value: "vaginalbleeding", label: "Vaginal Bleeding" },
  { value: "vaginaldischarge", label: "Vaginal Discharge" },
  { value: "vaginalpain", label: "Vaginal Pain" },
  { value: "weakness", label: "Weakness" },
  { value: "wheezing", label: "Wheezing" },
  { value: "withdrawal alcohol", label: "Alcohol Withdrawal" },
  { value: "woundcheck", label: "Wound Check" },
  { value: "woundinfection", label: "Wound Infection" },
  { value: "woundre evaluation", label: "Wound Re-evaluation" },
  { value: "wristinjury", label: "Wrist Injury" },
  { value: "wristpain", label: "Wrist Pain" },
].sort((a, b) => a.label.localeCompare(b.label));
