export interface ChiefComplaint {
  value: string;
  label: string;
}

/** All chief complaint categories known to the trained XGBoost model.
 *  `value` is the exact string expected by the model (from cc_* training columns).
 *  `label` is the human-readable display name. */
export const CHIEF_COMPLAINTS: ChiefComplaint[] = [
  { value: "abdominalcramping", label: "Grčevi u trbuhu" },
  { value: "abdominaldistention", label: "Nadutost trbuha" },
  { value: "abdominalpain", label: "Bol u trbuhu" },
  { value: "abdominalpainpregnant", label: "Bol u trbuhu (trudnoća)" },
  { value: "abnormallab", label: "Abnormalni laboratorijski nalaz" },
  { value: "abscess", label: "Apsces" },
  { value: "addictionproblem", label: "Problem ovisnosti" },
  { value: "agitation", label: "Agitacija" },
  { value: "alcoholintoxication", label: "Alkoholna intoksikacija" },
  { value: "alcoholproblem", label: "Problem s alkoholom" },
  { value: "allergicreaction", label: "Alergijska reakcija" },
  { value: "alteredmentalstatus", label: "Izmijenjeno stanje svijesti" },
  { value: "animalbite", label: "Ugriz životinje" },
  { value: "ankleinjury", label: "Povreda gležnja" },
  { value: "anklepain", label: "Bol u gležnju" },
  { value: "anxiety", label: "Anksioznost" },
  { value: "arminjury", label: "Povreda ruke" },
  { value: "armpain", label: "Bol u ruci" },
  { value: "armswelling", label: "Otok ruke" },
  { value: "assaultvictim", label: "Žrtva napada" },
  { value: "asthma", label: "Astma" },
  { value: "backpain", label: "Bol u leđima" },
  { value: "bleeding/bruising", label: "Krvarenje / modrica" },
  { value: "blurredvision", label: "Zamagljen vid" },
  { value: "bodyfluidexposure", label: "Izloženost tjelesnim tekućinama" },
  { value: "breastpain", label: "Bol u grudima" },
  { value: "breathingdifficulty", label: "Otežano disanje" },
  { value: "breathingproblem", label: "Problem s disanjem" },
  { value: "burn", label: "Opekotina" },
  { value: "cardiacarrest", label: "Srčani zastoj" },
  { value: "cellulitis", label: "Celulitis" },
  { value: "chestpain", label: "Bol u grudnom košu" },
  { value: "chesttightness", label: "Stezanje u grudima" },
  { value: "chills", label: "Drhtavica" },
  { value: "coldlikesymptoms", label: "Simptomi prehlade" },
  { value: "confusion", label: "Konfuzija" },
  { value: "conjunctivitis", label: "Konjunktivitis" },
  { value: "constipation", label: "Zatvor" },
  { value: "cough", label: "Kašalj" },
  { value: "cyst", label: "Cista" },
  {
    value: "decreasedbloodsugar symptomatic",
    label: "Snižen šećer u krvi (simptomatski)",
  },
  { value: "dehydration", label: "Dehidracija" },
  { value: "dentalpain", label: "Zubobolja" },
  { value: "depression", label: "Depresija" },
  { value: "detoxevaluation", label: "Detoks procjena" },
  { value: "diarrhea", label: "Dijareja" },
  { value: "dizziness", label: "Vrtoglavica" },
  { value: "drug/alcoholassessment", label: "Procjena droge / alkohola" },
  { value: "drugproblem", label: "Problem s drogom" },
  { value: "dyspnea", label: "Dispneja" },
  { value: "dysuria", label: "Dizurija (pečenje pri mokrenju)" },
  { value: "earpain", label: "Bol u uhu" },
  { value: "earproblem", label: "Problem s uhom" },
  { value: "edema", label: "Edem (otok)" },
  { value: "elbowpain", label: "Bol u laktu" },
  {
    value: "elevatedbloodsugar nosymptoms",
    label: "Povišen šećer u krvi (bez simptoma)",
  },
  {
    value: "elevatedbloodsugar symptomatic",
    label: "Povišen šećer u krvi (simptomatski)",
  },
  { value: "emesis", label: "Povraćanje" },
  { value: "epigastricpain", label: "Epigastrična bol" },
  { value: "epistaxis", label: "Epistaksa (krvarenje iz nosa)" },
  { value: "exposuretostd", label: "Izloženost spolnoj bolesti" },
  { value: "extremitylaceration", label: "Laceracija ekstremiteta" },
  { value: "extremityweakness", label: "Slabost ekstremiteta" },
  { value: "eyeinjury", label: "Povreda oka" },
  { value: "eyepain", label: "Bol u oku" },
  { value: "eyeproblem", label: "Problem s okom" },
  { value: "eyeredness", label: "Crvenilo oka" },
  { value: "facialinjury", label: "Povreda lica" },
  { value: "faciallaceration", label: "Laceracija lica" },
  { value: "facialpain", label: "Bol u licu" },
  { value: "facialswelling", label: "Otok lica" },
  { value: "fall", label: "Pad" },
  { value: "fall>65", label: "Pad (65+ godina)" },
  { value: "fatigue", label: "Umor" },
  { value: "femaleguproblem", label: "Ginekološki problem" },
  { value: "fever", label: "Temperatura" },
  { value: "fever 75yearsorolder", label: "Temperatura (75+ godina)" },
  {
    value: "fever 9weeksto74years",
    label: "Temperatura (9 sedmica - 74 godine)",
  },
  {
    value: "feverimmunocompromised",
    label: "Temperatura (imunokompromitirani)",
  },
  { value: "fingerinjury", label: "Povreda prsta" },
  { value: "fingerpain", label: "Bol u prstu" },
  { value: "fingerswelling", label: "Otok prsta" },
  { value: "flankpain", label: "Bol u boku" },
  { value: "follow upcellulitis", label: "Kontrola: celulitis" },
  { value: "footinjury", label: "Povreda stopala" },
  { value: "footpain", label: "Bol u stopalu" },
  { value: "footswelling", label: "Otok stopala" },
  { value: "foreignbodyineye", label: "Strano tijelo u oku" },
  { value: "fulltrauma", label: "Politrauma" },
  { value: "generalizedbodyaches", label: "Generalizirani bolovi u tijelu" },
  { value: "gibleeding", label: "Gastrointestinalno krvarenje" },
  { value: "giproblem", label: "Gastrointestinalni problem" },
  { value: "groinpain", label: "Bol u preponama" },
  { value: "hallucinations", label: "Halucinacije" },
  { value: "handinjury", label: "Povreda šake" },
  { value: "handpain", label: "Bol u šaci" },
  { value: "headache", label: "Glavobolja" },
  {
    value: "headache newonsetornewsymptoms",
    label: "Glavobolja (novi nastup)",
  },
  {
    value: "headache recurrentorknowndxmigraines",
    label: "Glavobolja (ponavljajuća / migrena)",
  },
  { value: "headachere evaluation", label: "Ponovna procjena glavobolje" },
  { value: "headinjury", label: "Povreda glave" },
  { value: "headlaceration", label: "Laceracija glave" },
  { value: "hematuria", label: "Hematurija (krv u mokraći)" },
  { value: "hemoptysis", label: "Hemoptiza (iskašljavanje krvi)" },
  { value: "hippain", label: "Bol u kuku" },
  { value: "homicidal", label: "Homicidalne misli" },
  { value: "hyperglycemia", label: "Hiperglikemija" },
  { value: "hypertension", label: "Hipertenzija" },
  { value: "hypotension", label: "Hipotenzija" },
  { value: "influenza", label: "Gripa" },
  { value: "ingestion", label: "Gutanje stranog tijela" },
  { value: "insectbite", label: "Ubod insekta" },
  { value: "irregularheartbeat", label: "Nepravilan srčani ritam" },
  { value: "jawpain", label: "Bol u vilici" },
  { value: "jointswelling", label: "Otok zgloba" },
  { value: "kneeinjury", label: "Povreda koljena" },
  { value: "kneepain", label: "Bol u koljenu" },
  { value: "laceration", label: "Laceracija (posjekotina)" },
  { value: "leginjury", label: "Povreda noge" },
  { value: "legpain", label: "Bol u nozi" },
  { value: "legswelling", label: "Otok noge" },
  { value: "lethargy", label: "Letargija" },
  { value: "lossofconsciousness", label: "Gubitak svijesti" },
  { value: "maleguproblem", label: "Urološki problem" },
  { value: "mass", label: "Kvržica / tumor" },
  { value: "medicalproblem", label: "Medicinski problem" },
  { value: "medicalscreening", label: "Medicinski pregled" },
  { value: "medicationproblem", label: "Problem s lijekom" },
  { value: "medicationrefill", label: "Dopuna lijekova" },
  { value: "migraine", label: "Migrena" },
  { value: "modifiedtrauma", label: "Modificirana trauma" },
  { value: "motorcyclecrash", label: "Motociklistička nesreća" },
  { value: "motorvehiclecrash", label: "Saobraćajna nesreća" },
  { value: "multiplefalls", label: "Višestruki padovi" },
  { value: "nasalcongestion", label: "Začepljen nos" },
  { value: "nausea", label: "Mučnina" },
  { value: "nearsyncope", label: "Predonesviješćenost" },
  { value: "neckpain", label: "Bol u vratu" },
  { value: "neurologicproblem", label: "Neurološki problem" },
  { value: "numbness", label: "Utrnulost" },
  { value: "oralswelling", label: "Otok u ustima" },
  { value: "otalgia", label: "Otalgia (bol u uhu)" },
  { value: "other", label: "Ostalo" },
  { value: "overdose accidental", label: "Predoziranje (slučajno)" },
  { value: "overdose intentional", label: "Predoziranje (namjerno)" },
  { value: "pain", label: "Bol (opšta)" },
  { value: "palpitations", label: "Palpitacije (lupanje srca)" },
  { value: "panicattack", label: "Napad panike" },
  { value: "pelvicpain", label: "Bol u karlici" },
  { value: "poisoning", label: "Trovanje" },
  { value: "post opproblem", label: "Postoperativni problem" },
  { value: "psychiatricevaluation", label: "Psihijatrijska procjena" },
  { value: "psychoticsymptoms", label: "Psihotični simptomi" },
  { value: "rapidheartrate", label: "Ubrzani srčani ritam" },
  { value: "rash", label: "Osip" },
  { value: "rectalbleeding", label: "Rektalno krvarenje" },
  { value: "rectalpain", label: "Rektalna bol" },
  { value: "respiratorydistress", label: "Respiratorni distres" },
  { value: "ribinjury", label: "Povreda rebra" },
  { value: "ribpain", label: "Bol u rebru" },
  { value: "seizure newonset", label: "Napad (novi nastup)" },
  { value: "seizure priorhxof", label: "Napad (ranije poznato)" },
  { value: "seizures", label: "Epileptički napadi" },
  { value: "shortnessofbreath", label: "Kratak dah" },
  { value: "shoulderinjury", label: "Povreda ramena" },
  { value: "shoulderpain", label: "Bol u ramenu" },
  { value: "sicklecellpain", label: "Bol srpaste anemije" },
  { value: "sinusproblem", label: "Sinusni problem" },
  { value: "skinirritation", label: "Iritacija kože" },
  { value: "skinproblem", label: "Problem s kožom" },
  { value: "sorethroat", label: "Upala grla" },
  { value: "stdcheck", label: "Pregled na spolne bolesti" },
  { value: "strokealert", label: "Moždani udar" },
  { value: "suicidal", label: "Suicidalne misli" },
  { value: "suture/stapleremoval", label: "Vađenje šavova / spajalica" },
  { value: "swallowedforeignbody", label: "Progutano strano tijelo" },
  { value: "syncope", label: "Sinkopa (gubitak svijesti)" },
  { value: "tachycardia", label: "Tahikardija" },
  { value: "testiclepain", label: "Bol u testisu" },
  { value: "thumbinjury", label: "Povreda palca" },
  { value: "tickremoval", label: "Vađenje krpelja" },
  { value: "toeinjury", label: "Povreda prsta na nozi" },
  { value: "toepain", label: "Bol u prstu na nozi" },
  { value: "trauma", label: "Trauma" },
  { value: "unresponsive", label: "Bez reakcije" },
  { value: "uri", label: "Infekcija gornjih disajnih puteva" },
  { value: "urinaryfrequency", label: "Učestalo mokrenje" },
  { value: "urinaryretention", label: "Zadržavanje mokraće" },
  { value: "urinarytractinfection", label: "Infekcija mokraćnih puteva" },
  { value: "vaginalbleeding", label: "Vaginalno krvarenje" },
  { value: "vaginaldischarge", label: "Vaginalni iscjedak" },
  { value: "vaginalpain", label: "Vaginalna bol" },
  { value: "weakness", label: "Slabost" },
  { value: "wheezing", label: "Zviždanje pri disanju" },
  { value: "withdrawal alcohol", label: "Alkoholni apstinencijalni sindrom" },
  { value: "woundcheck", label: "Provjera rane" },
  { value: "woundinfection", label: "Infekcija rane" },
  { value: "woundre evaluation", label: "Ponovna procjena rane" },
  { value: "wristinjury", label: "Povreda ručnog zgloba" },
  { value: "wristpain", label: "Bol u ručnom zglobu" },
].sort((a, b) => a.label.localeCompare(b.label));
